name: Build-Test

on:
  pull_request:
    branches: [ "main" ]
    
env:
  working-directory: ./DPC.Solution

jobs:

  sonar-cloud:
    uses: zealous-technology/DPC/.github/workflows/sonar-cloud.yml@main
    secrets: inherit
    with:
      working-directory: "./DPC.Solution"

  build-test:
    runs-on: ubuntu-latest
    needs: sonar-cloud
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
        
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
