name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  SOLUTION_PATH: ./DPC.Solution
  DOCKERFILE_PATH: ./DPC.Solution/DPC.Web

jobs:

  #code-analysis:
  #  uses: zealous-technology/DPC/.github/workflows/sonar-cloud.yml@main
  #  with:
  #    SOLUTION_PATH: "./DPC.Solution/DPC.Web"
  #  secrets: inherit

  build:
   # needs: code-analysis

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: ./DPC.Solution
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
         
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
             
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./DPC.Web
        push: true
        tags: steveager/dpc:latest
