name: SonarCloud
on:
  workflow_call:
    inputs:
      SOLUTION_PATH:
        required: true
        type: string
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: display_path
        run: echo ${{ input.SOLUTION_PATH }}
        
